#!/bin/bash
if [[ $EUID -ne 0 ]]; then
   echo "This installer must be run as root" 
   exit 1
fi

echo installing dependencies...

#pacman -S --needed gcc binutils tpm2-tools mkinitcpio python3 python3-pip
apt install -y binutils tpm2-tools python3 python3-pip
pip install signify
cp bytelocker /usr/bin/bytelocker
chmod +x /usr/bin/bytelocker
mkdir /var/lib/bytelocker

echo running setup
bytelocker setup
