#!/bin/bash
if [[ $EUID -ne 0 ]]; then
   echo "This installer must be run as root" 
   exit 1
fi

echo installing dependencies...

pacman -S --needed gcc binutils tpm2-tools mkinitcpio

echo compiling...
g++ -o /usr/bin/bytelocker bytelocker.cpp

if [ -f /usr/bin/bytelocker ] ; then
echo
 echo Installation successful
  fi
